### ISSUE TITLE
How do I roll attack with a weapon.

### ISSUE THREAD

**Issue by mrbwhitby** [Spice-King/foundry-swnr#15]
I love that you are developing this system module for Foundry.

Our group is trying out Stars Without Number. We have tried it out on Roll20 but Foundry is soooo much better. 

But I am unable to figure out how to roll attacks with the weapons.  An actor, once equiped with one of the weapons in the compendium, has a weapon on which a player can click on. It asks the pertinent questions.....but then no dice roll results from the click.
Are we doing something wrong.

and apologies for logging the question here in the "Issues" section. I wasn't sure where else to contact you through regarding your module.

Thanks so much for your module and your help.

**Comment by jwmccowan** [comment]
I was trying out the system this evening and found the same issue.  Throws an undefined error in the console.

Looks like [line 156](https://github.com/Spice-King/foundry-swnr/blob/83313deae45b849131082355f2c476951e65faa4/src/module/actors/character-sheet.ts#L156) (104 in the source map) in the character sheet is throwing an error, probably because the query selector on [line 135](https://github.com/Spice-King/foundry-swnr/blob/83313deae45b849131082355f2c476951e65faa4/src/module/actors/character-sheet.ts#L135) (91 in the source map) is returning undefined.

@Spice-King Do you accept pull requests?

**Comment by jwmccowan** [comment]
Ah I see what's going on here.  @mrbwhitby you can set the skill to use by editing the weapon itself from the weapons tab.  If you select `shoot` or whatever, it will use that value and roll correctly.

If you don't select a skill, the roll errors out.  There needs to be a check if `skill` exists before checking its value on line 156, something like:
```
effectiveSkillRank:
          !skill || skill.data.data.rank < 0 ? -2 : skill.data.data.rank,
```

**Comment by mrbwhitby** [comment]
Thanks so much! I will try that out.  This is much appreciated.

**Comment by Spice-King** [comment]
Ah sorry, missed the email yesterday. I'll look into why the prompt for what skill to use in the dialog is not there. I probably messed up the logic when I anded NPCs.
