### ISSUE TITLE
Rework bottom tabbed section

### ISSUE THREAD

**Issue by Spice-King** [Spice-King/foundry-swnr#8]
I'm not loving how it is.

At least weapon, armor and general inventory could get condensed into one tab with rework.
Skills, foci and powers are another possible set of tabs to merge.

**Comment by bwebster4** [comment]
For what it's worth, I kinda like it how it is. I could see combining foci and powers, but skills feel totally separate to me, and I wouldn't want them all cluttering each other on the same tab. Weapons and armor already kind of are on the general inventory, I could see combining them as long as weapons are still easily accessible to make attack rolls.

**Comment by detraya** [comment]
hey thanks for making this, but I agree with the bottom tab not being great. in particular the fact that the inventory is just one long list feels bad, since it leaves a bunch of empty space. if we could have multiple rows of inventory , or maybe condense the information down to one line instead of three, i'd go a long way to make it easier to play with this system.

**Comment by colonel-colony** [comment]
The Worlds Without Number Foundry VTT Character sheet does a decent job at breaking out the information in a tabbed form.  Don't need to replicate exactly but something like that would be nice.

**Comment by Spice-King** [comment]
Forgot I had this open, more or less sorted with 77995516557444dffa08671b2731d5de259557ce
